service: sls-with-preexisting-layer

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  timeout: 300

functions:
  chromium-test:
    handler: route.POST
    layers:
      - arn:aws:lambda:us-east-1:************:layer:chromium:*